### ISSUE TITLE
Lens shift in BGE  

### ISSUE THREAD

**Issue by ghost** [stuffmatic/blam#13]
Hi,
After successful 'BLAM'ing an using object using a data projector the object shifts in game mode. This appears to be due to the lens shift not working in game engine. I tried the code here:
http://wiki.blender.org/index.php/Doc:2.6/Manual/Game_Engine/Camera
(correcting the "shitfy" typo) and it didn't help. 
I'm using blender 2.72b

**Comment by tltmedia** [comment]
Thanks Steff777! That worked like a charm!
