### ISSUE TITLE
How to match the camera at ortho picture?

### ISSUE THREAD

**Issue by fatemax** [stuffmatic/blam#16]
Hi, how to match the camera at this picture [https://dl.dropboxusercontent.com/u/94590527/stairs.jpg](url)
blender 2.74
BLAM 0.6

**Comment by stuffmatic** [comment]
TL;DR Ortho image calibration is not currently possible.

BLAM relies on the existence of vanishing points to compute the camera transform. Since parallel lines remain parallel under an ortho projection, there are no vanishing points, which means BLAM won't be able to perform the calibration.
