### ISSUE TITLE
Can I obtain the focal length in pixel by giving some images ? 

### ISSUE THREAD

**Issue by shuluoshu** [stuffmatic/blam#36]
hi, @ideasman42  @stuffmatic , thank you for your share. I wonder if I don't have exif information, I only have some images, and I want to get the intrinsics, mainly the fx in pixel, how can I do with your "blam" ? Thanks.

**Comment by stuffmatic** [comment]
blam is no longer maintained. Have a look at fSpy instead https://github.com/stuffmatic/fSpy
